name: CI Checks

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install ruff pytest

      - name: Run Ruff (formatting check)
        run: ruff format --check

      - name: Run Ruff (linting check)
        run: ruff check .

      - name: Run tests with pytest
        run: pytest



